spring:
  application:
    name: border-service
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

zuul:
  ignored-services: '*'
  prefix: /app
  routes:
    producer:
      path: /producer/**
    consumer:
      path: /consumer/**
      
ribbon:
  eureka:
    enabled: true
    