spring:
  application:
    name: border-service
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

zuul:
  ignored-services: '*'
  prefix: /app
  routes:
    producer:
      service-id: producer
      path: /producer/**
      
    consumer:
      id: consumer
      path: /consumer/**

producer:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100    
      
ribbon:
  eureka:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    