spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafkaBalancedConsumer
    username: root
    password: example
    initialize: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  kafka:
    consumer:
      topicName: topicInbound
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      group-id: consumerGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      topicName: topicOutbound
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
