kafkaProducer:
  instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  concurrentProcessor:
    waitTimeout: 3000
  consumer:
    containerFactory:
      concurrency: 20
      properties:
        poolTimeout: 30000
  restTemplate:
    redirect:
      readTimeout: 1000
      connectTimeout: 500

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    appname: producer
    instance-id: producer-${random.value}

spring:
  application:
    name: producer
  kafka:
    consumer:
      topicName: topicOutbound
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      topicName: topicInbound
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
