kafkaConsummer:
  instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  responseConsumer:
    consumer:
      topicName: topicOutbound
  requestProcessor:
    waitTimeout: 3000
    
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    instance-id: producer-${random.value}
    prefer-ip-address: false

spring:
  application:
    name: producer
  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      # group-id: producerGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      topicName: topicInbound
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
